x = input('Digite algo:')
tp = type(x)
n = x.isnumeric()
a = x.isalpha()
an = x.isalnum()
u = x.isupper()
l = x.islower()
c = x.istitle()
print('O tipo primitivo é: {}'.format(tp))
print('É numérico? {}'.format(n))
print('É alfabético? {}'.format(a))
print('É alfanumérico? {}'.format(an))
print('Está em maiúsculas? {}'.format(u))
print('Está em minúsculas? {}'.format(l))
print('Está capitalizada? {}'.format(c))
# Exemplo sem usar a máscara:
print('Só tem espaços?', x.isspace())
