nome = str(input('Digite seu nome completo: ')).strip()
print(nome.lower())
print(nome.upper())
print('Seu nome completo contém {}{}{} caracteres.'.format('\033[1;36m', len(nome) - nome.count(' '), '\033[m'))
print('Seu primeiro nome contém {}{}{} caracteres.'.format('\033[1;36m', nome.find(' '), '\033[m'))
# print(len(nome.split()[0])))
